package com.koniukhov.cinecirclex.core.common.model

enum class MediaListType {
    NOW_PLAYING_MOVIES,
    TRENDING_MOVIES,
    POPULAR_MOVIES,
    TOP_RATED_MOVIES,
    UPCOMING_MOVIES,
    MOVIES_BY_GENRE,
    AIRING_TODAY_TV_SERIES,
    ON_THE_AIR_TV_SERIES,
    TRENDING_TV_SERIES,
    POPULAR_TV_SERIES,
    TOP_RATED_TV_SERIES,
    TV_SERIES_BY_GENRE
}