package com.koniukhov.cinecircle.core.domain.model

import com.koniukhov.cinecircle.core.common.Constants.INVALID_ID

data class TvSeriesDetails(
    val adult: Boolean,
    val backdropPath: String,
    val createdBy : List<Creator>,
    val episodeRunTime: List<Int>,
    val firstAirDate: String,
    val genres: List<Genre>,
    val homepage: String,
    val id: Int,
    val inProduction: Boolean,
    val languages: List<String>,
    val lastAirDate: String,
    val lastEpisodeToAir: TvEpisodeDetails,
    val name: String,
    val nextEpisodeToAir: TvEpisodeDetails?,
    val networks: List<Network>,
    val numberOfEpisodes: Int,
    val numberOfSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Float,
    val posterPath: String,
    val productionCompanies: List<ProductionCompany>,
    val productionCountries: List<ProductionCountry>,
    val seasons: List<TvSeasonDetails>,
    val spokenLanguages: List<Language>,
    val status: String,
    val tagline: String,
    val type: String,
    val voteAverage: Float,
    val voteCount: Int
) {
    companion object {
        fun empty() = TvSeriesDetails(
            adult = false,
            backdropPath = "",
            createdBy = emptyList(),
            episodeRunTime = emptyList(),
            firstAirDate = "",
            genres = emptyList(),
            homepage = "",
            id = INVALID_ID,
            inProduction = false,
            languages = emptyList(),
            lastAirDate = "",
            lastEpisodeToAir = TvEpisodeDetails.empty(),
            name = "",
            nextEpisodeToAir = null,
            networks = emptyList(),
            numberOfEpisodes = 0,
            numberOfSeasons = 0,
            originCountry = emptyList(),
            originalLanguage = "",
            originalName = "",
            overview = "",
            popularity = 0f,
            posterPath = "",
            productionCompanies = emptyList(),
            productionCountries = emptyList(),
            seasons = emptyList(),
            spokenLanguages = emptyList(),
            status = "",
            tagline = "",
            type = "",
            voteAverage = 0f,
            voteCount = 0
        )
    }
}